version: '3.1'

services:
  bf-postgre:
    image: postgres
    container_name: ${PGHOST}
    restart: always
    expose: 
      - "${PGPORT}"
    # ports:
    #   - "${PGPORT}:${PGPORT}"
    environment:
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
      - ./postgres-data:/var/lib/postgresql/data
  bf-server:
    build: .
    command: "npm start"
    restart: always
    container_name: ${VIRTUAL_HOST}
    ports:
      - "${PORT}:${PORT}"
    networks:
      - default
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - .:/app
      - /app/node_modules
    depends_on: 
      - bf-postgre

networks:
  default:
    external:
      name: webproxy