version: '3.7'

services:
  bf-postgre:
    image: postgres
    container_name: ${PGHOST}
    restart: always
    expose: 
      - "${PGPORT}"
    # ports:
    #   - "${PGPORT}:${PGPORT}"
    environment:
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${PGDATABASE}", "-U", "${PGUSER}" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
  bf-server:
    build: .
    command: "npm start"
    restart: always
    container_name: ${VIRTUAL_HOST}
    expose: 
      - "${PORT}"
    networks:
      - default
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - .:/app
      - /app/node_modules
    depends_on: 
      - bf-postgre
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "http://localhost:${PORT}"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    external:
      name: webproxy