version: '3.1'

services:
  bf-postgre:
    image: postgres
    container_name: babyfoot.db
    restart: always
    expose: 
      - "5432"
    # ports:
    # - "5432:5432"
    environment:
      POSTGRES_DB: babyfoot
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
  bf-server:
    build: .
    command: "npm start"
    container_name: babyfoot.server
    ports:
      - "3010:3000"
    networks:
      - default
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - .:/app
      - /app/node_modules

networks:
  default:
    external:
      name: webproxy