CREATE TABLE games 
(
  ID SERIAL PRIMARY KEY, 
  name VARCHAR(255) NOT NULL, 
  status VARCHAR(255) DEFAULT 'progress'
);

CREATE TABLE messages
(
  ID SERIAL PRIMARY KEY, 
  name VARCHAR(255) NOT NULL, 
  message TEXT NOT NULL
);